# Pi-hole configuration.
pihole_single_mode: true
pihole_image: pihole/pihole:2023.01.10
pihole_hostname: pihole
pihole_password: change-this-password

# Exporter Configuration
pihole_exporter_enable: false
pihole_exporter_image: ekofr/pihole-exporter:latest
