# # Pi-hole configuration.
pihole_enable: true
pihole_single_mode: true
pihole_image: pihole/pihole:2023.01.10
pihole_hostname: pihole
pihole_password: change-this-password

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: home.local
domain_pihole: pihole

# Exporter Configuration
pihole_exporter_enable: false
pihole_exporter_image: ekofr/pihole-exporter:latest
